codestates-seb/seb43_main_014

client/src/App.js, client/src/index.js
=> 💡 Init : dev 초기설정

client/.eslintrc.json, client/.prettierrc, client/.vscode/settings.json, client/package-lock.json, client/package.json, client/src/App.js, client/src/utils/GlobalStyle.js
💡 Init : eslint, prettier 초기 설정
=> 💡 Init : eslint, prettier, vscode 초기 설정

client/src/AppRocketCV.js, client/src/pages/Login.module.css, client/src/pages/Signup.jsx, client/src/pages/Signup.module.css
=> ✅ Style : 브런치 병합

server/build.gradle, server/src/main/java/com/cv/domain/audit/Auditable.java, server/src/main/java/com/cv/domain/audit/AuditorAwareImpl.java, server/src/main/java/com/cv/domain/user/dto/UserDto.java, server/src/main/java/com/cv/domain/user/entity/User.java, server/src/main/java/com/cv/domain/user/repository/UserRepository.java, server/src/main/java/com/cv/domain/user/validator/UserValidator.java, server/src/main/java/com/cv/domain/user/validator/ValidEmail.java
=> 💡 Init : MapStruct 라이브러리 추가

server/build.gradle, server/src/main/java/com/cv/global/advice/GlobalExceptionAdvice.java, server/src/main/java/com/cv/global/auth/dto/LoginDto.java, server/src/main/java/com/cv/global/auth/filter/JwtAuthenticationFilter.java, server/src/main/java/com/cv/global/auth/handler/UserAuthenticationFailureHandler.java, server/src/main/java/com/cv/global/auth/handler/UserAuthenticationSuccessHandler.java, server/src/main/java/com/cv/global/auth/jwt/JwtTokenizer.java, server/src/main/java/com/cv/global/auth/userdetails/UserDetailsService.java, server/src/main/java/com/cv/global/auth/utils/UserAuthorityUtils.java, server/src/main/java/com/cv/global/config/SecurityConfiguration.java, server/src/main/java/com/cv/global/exception/BusinessLogicException.java, server/src/main/java/com/cv/global/exception/ExceptionCode.java, server/src/main/java/com/cv/global/response/ErrorResponse.java
1. 예외 처리 로직 구현
GlobalExceptionAdvice, BusinessLogicException, ExceptionCode, ErrorResponse
비즈니스 로직 예외, 공통 예외 처리 로직 구현했습니다.
- 마음껏 필요한 예외 코드, 예외 처리 메서드 추가해주세요
2. 로그인 인증 및 JWT 생성 로직 구현
3. MySQL, Gson, Security, JJWT 의존성 주입했습니다.
- MySQL 의존성이 h2 의존성이랑 충돌날 수 있음 -> 확인부탁드립니다
=> ✨ Feat : 예외 처리, 로그인 인증, gradle 의존성 추가

server/build.gradle, server/src/main/java/com/cv/domain/user/dto/UserDto.java, server/src/main/java/com/cv/domain/user/mapper/UserMapper.java
componentModel 버전문제로 1.5.x로 변경
=>  💡 Init : MapStruct 라이브러리 버전변경

server/src/main/java/com/cv/domain/user/controller/UserController.java, server/src/main/java/com/cv/domain/user/entity/User.java, server/src/main/java/com/cv/domain/user/entity/UserSkillStack.java, server/src/main/java/com/cv/domain/user/service/UserService.java
이미지는 일단 string 타입으로 두었어요! 
서비스로직은 주석처리 해놨어요!
=> ✨ Feat : user엔티티 작성

client/src/components/MyPage/DeleteAccount/DeleteModal/deleteModal.module.css, client/src/components/MyPage/DeleteAccount/DeleteModal/index.jsx, client/src/components/MyPage/DeleteAccount/deleteAccount.module.css, client/src/components/MyPage/DeleteAccount/index.jsx, client/src/components/MyPage/Profile/ProfileUpdata/ProfileUpdata.jsx, client/src/components/MyPage/PwChange/PwChange.jsx, client/src/components/MyPage/PwChange/PwModal/PwModal.jsx, client/src/components/MyPage/PwChange/PwModal/pwModal.module.css, client/src/components/MyPage/PwChange/pwChange.module.css, client/src/components/common/Modal/index.jsx, client/src/components/common/Modal/modal.module.css
✨ Feat : 모달 컴포넌트 추가.(재사용)
🔨 Refactor : 코드 정리
=> 🔨 Refactor : 코드 정리

client/src/components/MyPage/Profile/Profile.jsx, client/src/components/MyPage/Profile/ProfileUpdata/ProfileUpdata.jsx, client/src/components/MyPage/Profile/ProfileUpdata/profileUpdata.module.css
🔨 Refactor : 전화 번호 유효성 검사 수정, 코드 수정
=> 🔨 Refactor : 전화 번호 유효성 검사 수정, 코드 수정  

client/src/components/MyPage/DeleteAccount/DeleteModal/deleteModal.module.css, client/src/components/MyPage/DeleteAccount/DeleteModal/index.jsx, client/src/components/MyPage/DeleteAccount/index.jsx, client/src/components/MyPage/Profile/Profile.jsx, client/src/components/MyPage/Profile/ProfileCard/ProfileCard.jsx, client/src/components/MyPage/Profile/ProfileUpdata/ProfileUpdata.jsx, client/src/components/MyPage/Profile/ProfileUpdata/profileUpdata.module.css, client/src/components/MyPage/PwChange/PwModal/PwModal.jsx, client/src/pages/MyPage/MyPage.jsx
✨ Feat : 비밀번호 유효성 검사 추가
🔨 Refactor : props 수정
=> ✨ Feat : 비밀번호 유효성 검사 추가

client/src/components/Cv/Footer.jsx, client/src/components/Cv/Header.jsx, client/src/components/common/LabelInput/LabelInput.jsx, client/src/components/common/LabelInput/LabelInput.module.css
=> Fe feat/login

client/src/components/MyPage/CvList/index.jsx, client/src/components/MyPage/PwChange/PwModal/PwModal.jsx, client/src/components/MyPage/PwChange/PwModal/pwModal.module.css, client/src/pages/MyPage/mypage.module.css
🔨 Refactor : 유효성 검사 조건 만족 못하면 비밀번호 변경 버튼 비활성화
https://github.com/codestates-seb/seb43_main_014/assets/97542179/6ae1bbd0-7a66-4737-bea4-93f699fa6e99
=> Fe feat/mypage

client/src/components/Cv/CvBasicInfo.jsx, client/src/components/Cv/CvCareer.jsx, client/src/components/Cv/EventTap.jsx
=> 🎨 Design : CvBasicInfo Tag add

client/src/components/Cv/CvBasicInfo.jsx, client/src/components/Cv/CvCareer.jsx, client/src/components/Cv/data.jsx
=> ✨ Feat : Input onChange add

client/src/components/MyPage/DeleteAccount/DeleteModal/index.jsx, client/src/components/MyPage/Profile/ProfileUpdata/ProfileUpdata.jsx, client/src/components/MyPage/Profile/ProfileUpdata/profileUpdata.module.css, client/src/components/MyPage/PwChange/PwModal/PwModal.jsx, client/src/pages/MyPage/MyPage.jsx
✨ Feat : 이미지 수정 추가
🔨 Refactor : CRUD
=> ✨ Feat : 이미지 수정 추가

server/src/main/java/com/cv/domain/cv/entity/Cv.java, server/src/main/java/com/cv/domain/cv/repository/CvRepository.java, server/src/main/java/com/cv/domain/cv/service/CvService.java, server/src/main/java/com/cv/domain/user/controller/UserController.java, server/src/main/java/com/cv/domain/user/service/UserService.java, server/src/main/java/com/cv/global/audit/AuditorAwareImpl.java, server/src/main/java/com/cv/global/config/SecurityConfiguration.java
테스트 코드는 아직 작성 못했습니다. 포스트맨으로는 테스트 완료했어요!
=> ✨ Feat : 마이페이지 전체조회, 비밀번호 변경 test 완료!

server/src/main/java/com/cv/domain/user/controller/UserController.java, server/src/main/java/com/cv/domain/user/dto/UserDto.java
✨ Feat : 비번변경에 수정시간 추가하기,
이미지경로 dto로 받기로 수정
=> ✨ Feat : 비번변경에 수정시간 추가하기,  이미지경로 파람-> dto로 받기로 수정

client/src/AppRocketCV.js, client/src/components/MyPage/Profile/ProfileCard/ProfileCard.jsx, client/src/components/MyPage/Profile/ProfileUpdata/ProfileUpdata.jsx
=> 🔨 Refactor : img 변경

server/src/main/java/com/cv/domain/cv/dto/PageLatestCvDto.java, server/src/main/java/com/cv/domain/user/controller/UserController.java, server/src/main/java/com/cv/domain/user/service/DefaultUserService.java, server/src/main/java/com/cv/domain/user/service/ReadOnlyUserService.java
✨ Feat : 마이페이지 내 페이지네이션 cvId 추가, createdAt의 이력서 작성 시간은 제외해서 보내기, 에러해결
=> ✨ Feat : 마이페이지 내 페이지네이션 수정 

client/src/components/Cv/CvBasicInfo.jsx, client/src/components/Cv/CvCareer.jsx, client/src/components/Cv/TagInput.jsx, client/src/components/Cv/UserCv.jsx
기술 스택 추가 및 이력서 제목, 성명 항목 유효성 검사 추가, 유저이력서 컴포넌트 구현
=> ✨ Feat : 기술 스택, 유효성 검사, 유저이력서 구현

client/.gitignore, client/src/components/MyPage/CvList/cvList.module.css, client/src/components/MyPage/CvList/index.jsx, client/src/components/MyPage/Profile/ProfileCard/ProfileCard.jsx, client/src/components/MyPage/Profile/ProfileUpdata/ProfileUpdata.jsx, client/src/pages/MyPage/MyPage.jsx
=> ✨ Feat : 이력서 수정, 삭제 추가

client/src/components/MyPage/CvList/cvList.module.css, client/src/components/MyPage/CvList/index.jsx, client/src/components/MyPage/Profile/ProfileCard/ProfileCard.jsx, client/src/components/MyPage/Profile/ProfileUpdata/ProfileUpdata.jsx, client/src/components/MyPage/PwChange/PwChange.jsx, client/src/components/MyPage/PwChange/PwModal/PwModal.jsx, client/src/pages/MyPage/MyPage.jsx, client/src/pages/MyPage/mypage.module.css
✨ Feat : ACCESS_KEY env 사용 
✨ Feat : 이력서 수정 추가
=> ✨ Feat : ACCESS_KEY env 사용 

client/src/components/Cv/CvBasicInfo.jsx, client/src/components/Cv/CvCareer.jsx, client/src/components/Cv/CvPage.jsx, client/src/components/Cv/EditCv.jsx, client/src/components/Cv/UserCv.jsx
임시저장, CV CRUD 구현 clear
서버쪽 데이터 관련 수정 필요.
=> ✨ Feat : 임시저장, CV CRUD 구현 clear

client/package-lock.json, client/src/components/Cv/CvCareer.jsx, client/src/components/Cv/CvSample.jsx, client/src/components/Cv/EditCv.jsx, client/src/components/Cv/UserCv.jsx
=> ⚠ Fix : EditCv bug Fix

client/src/components/MyPage/CvList/index.jsx, client/src/components/MyPage/DeleteAccount/DeleteModal/index.jsx, client/src/components/MyPage/DeleteAccount/index.jsx, client/src/components/MyPage/PwChange/PwChange.jsx, client/src/components/MyPage/PwChange/PwModal/PwModal.jsx, client/src/pages/MyPage/MyPage.jsx
=> ✨ Feat : 로그아웃 요청 추가

client/src/components/Cv/CvBasicInfo.jsx
윈도우와 맥 에서 다르게 보이는 Input을 수정했습니다. *테스트필요
=> 🎨 Design : CvBasicInfo birthInput css 수정

server/src/main/java/com/cv/domain/cv/service/CvService.java, server/src/main/java/com/cv/domain/user/controller/UserController.java, server/src/main/java/com/cv/domain/user/dto/sign/SignUpResponseDto.java, server/src/main/java/com/cv/domain/user/entity/User.java, server/src/main/java/com/cv/domain/user/repository/UserRepository.java, server/src/main/java/com/cv/domain/user/service/DefaultUserService.java, server/src/main/java/com/cv/domain/user/service/ReadOnlyUserService.java, server/src/main/java/com/cv/domain/user/service/UserServiceInter.java, server/src/main/java/com/cv/global/audit/Auditable.java, server/src/main/java/com/cv/global/auth/jwt/service/UserDetailsService.java
userId를 사용하는 곳에서 외부로 노출되는 부분은 모두 uuid로 수정하였습니당
=> 🔨 Refactor : userId -> uuid

server/src/main/java/com/cv/domain/user/service/UserServiceInter.java
user의 service - 인터페이스 확인하시면 주석부분 보시고 작성하시면 되요!
=> 🔨 Refactor : Javadoc 적용

client/src/components/Cv/CvBasicInfo.jsx, client/src/pages/Main.jsx
=> ✨ Feat : 이력서 이미지 업로드 미완

server/src/main/resources/db/migration/V1.0__init.sql
=> ✨ Feat : flyway 적용하기

server/src/main/java/com/cv/domain/cv/controller/CvControllerHelper.java, server/src/main/java/com/cv/domain/cv/dto/cvDto/CvPostDto.java, server/src/main/java/com/cv/domain/cv/dto/cvDto/CvResponseDto.java, server/src/main/java/com/cv/domain/cv/mapper/CvMapper.java, server/src/main/java/com/cv/domain/cv/service/CvServiceImpl.java, server/src/main/java/com/cv/domain/user/dto/sign/SignUpResponseDto.java, server/src/main/java/com/cv/domain/user/entity/User.java, server/src/main/resources/db/migration/V1.0__init.sql
🔨 Refactor: flyway 적용 및 규칙적용 (대문자사용x / 기존 table생성시 연결하는 방식에서 -> alter table로 변경 )
=> 🔨 Refactor: flyway 적용 및 규칙적용 (대문자사용x / 기존 table생성시 연결하는 방식에서 -> alter table로 변경 )

client/src/components/Cv/CvBasicInfo.jsx, client/src/components/Cv/CvCareer.jsx, client/src/components/Cv/CvPreview.jsx, client/src/components/Cv/CvSample.jsx, client/src/components/Cv/EditCv.jsx, client/src/components/Cv/TagInput.jsx, client/src/components/Cv/UserCv.jsx, client/src/pages/Main.jsx
이력서 작성에 용이하게 버튼 재배치 및 스킬스택 부분 수정
=> 🎨 Design : 사용자 편의를 위한 인터페이스 재배치

server/src/main/java/com/cv/domain/cv/repository/CvRepository.java, server/src/main/java/com/cv/domain/user/entity/User.java, server/src/main/java/com/cv/domain/user/service/UserServiceUtils.java, server/src/main/java/com/cv/global/audit/Auditable.java, server/src/main/java/com/cv/global/auth/jwt/filter/JwtAuthenticationFilter.java, server/src/main/java/com/cv/global/auth/oauth2/controller/OAuthController.java, server/src/main/java/com/cv/global/auth/oauth2/handler/OAuth2UserSuccessHandler.java, server/src/main/resources/db/migration/V1.0__init.sql, server/src/test/groovy/DefaultUserServiceTest.groovy, server/src/test/java/com/cv/service/CvServiceImplUnitTest.java
- rename: userId -> id로 변경 
: userId였을 때 jap가 user.userid로 인식하면서 테이블명과 맞지 않아 매칭하지 못하는 문제 발생
- User엔티티에서 @Data -> @getter,@setter로 변경 data애너테이션은 toString이 포함되어있어서 리소스발생으로 무한루프 돌 가능성이 있다고함.
- flaway에서 user_roles 테이블 없어서 에러발생, 테이블 추가함
=> 🚑  Fix : 버그 수정

client/package-lock.json, client/package.json, client/src/components/Cv/CvBasicInfo.jsx, client/src/components/Cv/CvCareer.jsx, client/src/components/Cv/CvPage.jsx, client/src/components/Cv/CvPreview.jsx
=> ✨ Feat : 이력서 PDF 다운로드 기능 추가

client/src/components/Cv/CvPreview.jsx, client/src/components/Cv/UserCv.jsx
1. 개발자 직무 항목이 중요도에 의해 위쪽으로 옮겨짐
2. 포트폴리오 링크 항목이 중요도에 의해 위쪽으로 옮겨짐
3. 교육사항 항목은 새로 제작된 템플릿에 적용하기로 함
4. 기술스택 보완 중
=> 🎨 Design : 부팀장님 수정사항 반영 (1,2,4)

server/src/main/java/com/cv/domain/user/controller/UserController.java, server/src/main/java/com/cv/domain/user/service/UserInfoService.java, server/src/main/java/com/cv/domain/user/service/UserInfoServiceInterface.java
=> ## 🚑  Fix : 컨트롤러 내 페이지네이션부분 서비스계층으로 분리

server/src/main/java/com/cv/domain/user/service/UserInfoService.java, server/src/main/java/com/cv/domain/user/service/UserInfoServiceInterface.java
- 컨트롤러 내 페이지네이션부분 서비스계층으로 분리 (오타수정)
=> ## 🚑  Fix : 컨트롤러 내 페이지네이션부분 서비스계층으로 분리 (오타수정)
